### ISSUE TITLE
Build hangs on AnalyseJavaParserTest

### ISSUE THREAD

**Issue by matozoid** [ftomassetti/java-symbol-solver#34]
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.203 sec
Running me.tomassetti.symbolsolver.resolution.ContextTest
Tests run: 23, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.315 sec
Running me.tomassetti.symbolsolver.resolution.AnalyseJavaParserTest
(nothing happens anymore)

**Comment by ftomassetti** [comment]
How long did you run it? Because it takes VERY long: it is parsing all JavaParser code and solving all symbols, verifying all symbols are the same expected in some test documents.

```
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 136.441 sec - in me.tomassetti.symbolsolver.resolution.AnalyseJavaParserTest
```

**Comment by matozoid** [comment]
Running me.tomassetti.symbolsolver.resolution.AnalyseJavaParserTest
Tests run: 11, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 239.463 sec

Alright then...
