### ISSUE TITLE
Get Declaration for Type

### ISSUE THREAD

**Issue by mlangkabel** [ftomassetti/java-symbol-solver#40]
Today I've got another problem: Is it possible to fetch the `com.github.javaparser.ast.body.ClassOrInterfaceDeclaration` for a `com.github.javaparser.ast.type.ClassOrInterfaceType`?

I've seen that the `JavaParserFacade` can be used to convert a `Type` and a `Node` to a `TypeUsage` (right now I don't know which node to pass to that method). Afterwards the `TypeUsage` can be used to get the type's declaration (which is a `me.tomassetti.symbolsolver.model.declarations.TypeDeclaration`). I guess the `wrappedNode` of this declaration is what I'm looking for, but in the current implementation of the Java Symbol Solver it is a private field. Is it possible to add a public getter for this field?

The reason I need access to the AST node is type name resolution as discussed in #37.

**Comment by ftomassetti** [comment]
Well, yes we could do that but TypeDeclaration could correspond to classes obtained through reflection or from jars. Only in the case they derives from JavaParser nodes you would be able to access it.

**Comment by mlangkabel** [comment]
That would be perfectly fine! :)

**Comment by ftomassetti** [comment]
I think that once you have the TypeDeclaration you could check if it is an instance of JavaParserClassDeclaration or JavaParserInterfaceDeclaration. If that is the case you can call getWrappedNode and get what you need.

**Comment by mlangkabel** [comment]
That sounds good.

In case the Type was resolved using the `JarTypeSolver` or the `JreTypeSolver` there is no Javaparser AST. So it's reasonable that classes used here do not offer any `getWrappedNode` method. I'll just use the `getQualifiedName` as a fallback. 

But if there is an AST node for that Type I'll need to use that node to resolve the name. This ensures that these types are always referred to using the same name (when indexing the Type's declaration **and** when indexing its usages).

**Comment by mlangkabel** [comment]
Oh, I just noticed that the `getWrappedNode` methods already exist! Initially I opened this issue to request adding them to the Java Symbol Solver. I feel a little dumb right now ;)

**Comment by ftomassetti** [comment]
Consider that you want to access the wrapped node just to handle local classes. But you will not see any local classes outside the method, so you should be covered, because the only local classes you will see will come from source code, not compiled code

**Comment by mlangkabel** [comment]
Exactly. It seems to be working as expected. Thank you for your guidance.

**Comment by ftomassetti** [comment]
Thank you for your interest in the project and let me know if I can help further

**Comment by mlangkabel** [comment]
Actually there is one more thing. Converting the `javaparser...ClassOrInterfaceType` to a `symbolsolver...TypeDeclaration` still gives me a headache.

There is a `JavaParserFacade.convert` method but most of the time it is throwing an UnsolvedSymbolException like the following:
```
Exception in thread "Thread-3" UnsolvedSymbolException{context='unknown', name='AnnotationDeclaration', typeSolver=null}
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convertToUsage(JavaParserFacade.java:440)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:483)
        at me.tomassetti.symbolsolver.javaparsermodel.JavaParserFacade.convert(JavaParserFacade.java:479)
        at io.coati.JavaTypeNameResolver.getTypeName(JavaTypeNameResolver.java:29)
       ...
```

I think it's possible that I'm providing the wrong context when calling the method like that: `convert(type, type)`. Can you please give me a hint what node I should provide as the second parameter?

**Comment by mlangkabel** [comment]
Oh, calling `convert(type, type)` seems to be totally alright! I guess the second parameter of this method can be used to skip some context layers, but passing the same node here as for the first argument is working fine as well.

In my case the issue was a totally different story. I was not creating my JavaParserTypeSolvers correctly, but didn't find out right away. I was only looking at the innermost context, not at the `CompilationUnitContext`.
