### ISSUE TITLE
UnsupportedOperationException in TypeDeclaration.getDeclaredMethods()

### ISSUE THREAD

**Issue by mlangkabel** [ftomassetti/java-symbol-solver#48]
This exception is thrown when the `TypeDeclaration` is actually a `JavaParserClassDeclaration` or a `JavaParserEnumDeclaration`. It seems like this method simply has not been implemented yet.

**Comment by mlangkabel** [comment]
Opened pull request #50

**Comment by ftomassetti** [comment]
Fixed by #50
