### ISSUE TITLE
Responsibility of JavaParserXxxDeclaration vs XxxContext

### ISSUE THREAD

**Issue by mlangkabel** [ftomassetti/java-symbol-solver#53]
On the one hand side the `JavaParserClassDeclaration` has a method `solveMethod` that just asks the respective context to solve the method. 

On the other hand side the method `solveType` is implemented in the `JavaParserClassDeclaration` and the respective context (in this case it's the `ClassOrInterfaceDeclarationContext`) just calls this implementation so solve a type.

So for me it seems a little unclear who's responsible for solving symbols, methods and types. The `JavaParserXxxDeclaration` or the `XxxContext`?

**Comment by mlangkabel** [comment]
I read some more of this project's codebase and I guess that the `Context` classes are in general responsible for solving symbols and types while the `Declaration` classes are just providing data.

Is that correct?

**Comment by ftomassetti** [comment]
Yes, I would say this is the main difference. The scoping rules should be part of Context and not of declarations, in my opinion. Also, contexts are useful to solve symbols in source code, while declarations can derive from source code but also from compiled code.

**Comment by mlangkabel** [comment]
Thanks for clarifying :)
