### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by ftomassetti** [ftomassetti/java-symbol-solver#62]
Ok, @mlangkabel provided enough fixes that it makes sense to do a new release

**Comment by matozoid** [comment]
Coming weekend I'll release JP alpha 3 with some interesting changes :)

**Comment by ftomassetti** [comment]
It will be the perfect time to release 0.3.1 :)

**Comment by matozoid** [comment]
I would love some feedback about the changes in alpha 3!

**Comment by ftomassetti** [comment]
Sure, for now moving to alpha 2 was pretty straightforward
