### ISSUE TITLE
java.util.Arrays asList

### ISSUE THREAD

**Issue by Pouja** [ftomassetti/java-symbol-solver#7]
Awesome tool this!

But I get an error when using ```Arrays.asList```, see the following case.

Extend the generics.java.txt to:
```java
package me.tomassetti.symbolsolver.javaparser;

import java.util.Optional;
import java.util.List;
import java.util.Arrays;

public final class Generics {

    Optional<String> s;
    Optional<Integer> i;
    Optional<Generics> g;

}

public final class SomeCollection<A> {

    public A a;
    public List<A> as;

    public void foo1(){
        new SomeCollection<String>().a;
    }

    public void foo2(){
        new SomeCollection<String>().as;
    }

    public List<Long> foo3(){
        return Arrays.asList(new Long[]{1L,2L});
    }

}
```

Create the function:
```java
    @Test
    public void blaat() throws ParseException {
        CompilationUnit cu = parseSample("Generics");
        ClassOrInterfaceDeclaration clazz = Navigator.demandClass(cu, "SomeCollection");

        MethodDeclaration method = Navigator.demandMethod(clazz, "foo3");

        ReturnStmt stmt = (ReturnStmt)method.getBody().getStmts().get(0);
        Expression expression = stmt.getExpr();
        TypeUsage typeUsage = JavaParserFacade.get(new JreTypeSolver()).getType(expression);
}
```

You will get the error:
```
Unsolved symbol in ReflectionClassDeclaration{clazz=java.util.Arrays} : Method 'asList' with parameterTypes [ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.Long}, typeParameters=[]}]
UnsolvedSymbolException{context='ReflectionClassDeclaration{clazz=java.util.Arrays}', name='Method 'asList' with parameterTypes [ReferenceTypeUsage{declaration=ReflectionClassDeclaration{clazz=java.lang.Long}, typeParameters=[]}]', typeSolver=null}
	at me.tomassetti.symbolsolver.resolution.javaparser.contexts.MethodCallExprContext.solveMethodAsUsage(MethodCallExprContext.java:96)
	at me.tomassetti.symbolsolver.resolution.javaparser.JavaParserFacade.solveMethodAsUsage(JavaParserFacade.java:394)
	at me.tomassetti.symbolsolver.resolution.javaparser.JavaParserFacade.getTypeConcrete(JavaParserFacade.java:150)
	at me.tomassetti.symbolsolver.resolution.javaparser.JavaParserFacade.getType(JavaParserFacade.java:116)
	at me.tomassetti.symbolsolver.resolution.javaparser.JavaParserFacade.getType(JavaParserFacade.java:110)
	at me.tomassetti.symbolsolver.resolution.GenericsTest.blaat(GenericsTest.java:185)
 ....
```

Any idea why?

**Comment by ftomassetti** [comment]
Thank you for your nice words and for your interest in this project. This project is fairly recent (even if it is almost complete) and bug reports really help me at this point.
In this case I think this is failing because the method invoked use variadic parameters which are not currently handled correctly. In this case you pass an Array of Long to a method taking a `Long...`, which is legal but it is one of the few corner features I still need to implement. Let's see if I can find a solution to this one in reasonable time.

**Comment by ftomassetti** [comment]
I have implemented an initial solution but it needs some more work to derive the return type correctly when varargs and generic are used together like in this case.

In the example the return type ot Arrays.toList(T...) depends on the value passed to Arrays.toList and it is not super trivial to derive it.

**Comment by ftomassetti** [comment]
This particular issue should be now solved, but we need far more tests on generics inference and to refactor the code involved with that.

**Comment by Pouja** [comment]
Just tested it with my code and it works. It correctly solves Arrays.asList now. Thanks!

**Comment by ftomassetti** [comment]
Great to hear that and thanks for testing it!

**Comment by Pouja** [comment]
Btw, any plans on publishing this to the central maven repo?

**Comment by ftomassetti** [comment]
Sure: snapshots are already available on https://oss.sonatype.org/content/repositories/snapshots

**Comment by Pouja** [comment]
:+1:

**Comment by ftomassetti** [comment]
BTW also version 0.1.3 has been released, just in case you need it
