### ISSUE TITLE
Tests are failing on Windows

### ISSUE THREAD

**Issue by mlangkabel** [ftomassetti/java-symbol-solver#70]
When running the java-symbol-solver-core tests on Windows I get errors like this one:
`org.junit.ComparisonFailure: Line 1 of src/test/resources/javaparser_expected_output/com_github_javaparser_ast_stmt_CatchClause.txt is different from what is expected expected:<[
]> but was:<[]>`

When re-generating the expected output files and using git to compare them to the original ones, it says that they have been modified but I cannot see any changes. Maybe it's a line endings thing.

**Comment by ftomassetti** [comment]
We need to add support for AppVeyor (basically Travis for Windows) to avoid this to get unnoticed in the future

**Comment by mlangkabel** [comment]
That would be great!

**Comment by mlangkabel** [comment]
Ok, I was able to fix the tests by adding a trim to the expected output and the generated output. Now the tests seem to be running fine. 

I'm still having an issue because my JVM running the tests runs out of memory during the `AnalyseJavaParserTest`s. Clearing the JavaParserFacades after each call to `parse(...)` reduces the required amount of memory a lot and fixes this issue for me.

**Comment by mlangkabel** [comment]
Created a pull request (#71) for these changes, please provide some feedback (or just accept it).

**Comment by matozoid** [comment]
Every Windows-specific compilation problem of JavaParser has been traced back to end of line characters. Feel free to use Utils.EOL :-)

**Comment by mlangkabel** [comment]
Thanks @matozoid for pointing me there. As far as I can see the problem is that the JavaSymolSolver's tests parses and solves some source files. Then it compares the generated output line by line to the content of files that contain the expected output. 
These expected-output-files have probably been written on a unix system and are now read on a windows system, screwing up with the line endings.
Even though each generated line's content matches the content of the same line in the expected-output-file, there are still some blank-space-characers appended that don't match. 
So I think trimming both strings that get compared is a good option because the content that matters does not get changed.

**Comment by matozoid** [comment]
I wasn't implying your fix isn't correct. I just like dropping random remarks in @ftomassetti 's project :)

**Comment by mlangkabel** [comment]
I know :) Just wanted to dump my mind because I wanted some feedback on whether or not that fix would cause any trouble.

**Comment by mlangkabel** [comment]
Fixed with merge of pull request #71.
